const questions = [
    {
      id: 1,
      title: 'NAME LIST - DIF GRANTEES - Fiscal Year 2022 ',
      info1: '- Alum Rock Union School District ',
      info2: '- Catholic Charities of Santa Clara County ',
      info3: '- Closing the Divide',
      info4: '- Evergreen Valley College',
      info5: '- Goodwill of Silicon Valley',
      info6: '- International Children Assistance Network',
      info7: '- International Rescue Committee',
      info8: '- Prosperity Lab',
      info9: '- Sacred Heart Community Service',
      info10: '- San Jose Community Media Access Corp',
      info11: '- Silicon Valley Education Foundation',
      info12: '- Sourcewise',
      info13: '- Step Up & Do Something! and Gates Consulting Group',
      info14: '- Tech Exchange',
      info15: '- Vietnamese Voluntary Foundation',
      ifOpen: true,
      },
    {
      id: 2,
      title: 'NAME LIST - DIF GRANTEES - Fiscal Year 2021 ',
      ifOpen: false,
      info1: '- Alum Rock Union School District ',
      info2: '- Catholic Charities of Santa Clara County ',
      info3: '- Closing the Divide',
      info4: '- Evergreen Valley College',
      info5: '- Goodwill of Silicon Valley',
      info6: '- International Children Assistance Network',
      info7: '- International Rescue Committee',
      info8: '- Prosperity Lab',
      info9: '- Sacred Heart Community Service',
      info10: '- San Jose Community Media Access Corp',
      info11: '- Silicon Valley Education Foundation',
      info12: '- Sourcewise',
      info13: '- Step Up & Do Something! and Gates Consulting Group',
      info14: '- Tech Exchange',
      info15: '- Vietnamese Voluntary Foundation',
      info:
        'Coloring book forage photo booth gentrify lumbersexual. Migas chillwave poutine synth shoreditch, enamel pin thundercats fashion axe roof party polaroid chartreuse.',
    },
    {
      id: 3,
      title: 'NAME LIST - DIF GRANTEES - Fiscal Year 2020',
      ifOpen: false,
      info1: '·Alum Rock Union School District ',
      info2: 'Catholic Charities of Santa Clara County ',
      info3: 'Closing the Divide',
      info4: 'Evergreen Valley College',
      info5: 'Goodwill of Silicon Valley',
      info6: 'International Children Assistance Network',
      info7: 'International Rescue Committee',
      info8: 'Prosperity Lab',
      info9: 'Sacred Heart Community Service',
      info10: 'San Jose Community Media Access Corp',
      info11: 'Silicon Valley Education Foundation',
      info12: 'Sourcewise',
      info13: 'Step Up & Do Something! and Gates Consulting Group',
      info14: 'Tech Exchange',
      info15: 'Vietnamese Voluntary Foundation',
      info16: 'Catholic Charities of Santa Clara County ',
      info:
        'Enamel pin fam sustainable woke whatever venmo. Authentic asymmetrical put a bird on it, lumbersexual activated charcoal kinfolk banjo cred pickled sartorial.',
    },
   
  ]
  export default questions