const questions = [
    {
      id: 1,
      title: 'DIF GRANTEES - Fiscal Year 2022 ',
      info1: '- Alum Rock Union School District ',
      info2: '- Catholic Charities of Santa Clara County ',
      info3: '- Closing the Divide',
      info4: '- Evergreen Valley College',
      info5: '- Goodwill of Silicon Valley',
      info6: '- International Children Assistance Network',
      info7: '- International Rescue Committee',
      info8: '- Prosperity Lab',
      info9: '- Sacred Heart Community Service',
      info10: '- San Jose Community Media Access Corp',
      info11: '- Silicon Valley Education Foundation',
      info12: '- Sourcewise',
      info13: '- Step Up & Do Something! and Gates Consulting Group',
      info14: '- Tech Exchange',
      info15: '- Vietnamese Voluntary Foundation',
      ifOpen: true,
      },
    {
      id: 2,
      title: 'DIF GRANTEES - Fiscal Year 2021 ',
      ifOpen: false,
      info1: '- CreaTV San Jose ',
      info2: '- Cristo Rey San José High School ',
      info3: '- Goodwill of Silicon Valley',
      info4: '- Evergreen Valley College',
      info5: '- Goodwill of Silicon Valley',
      info6: '- International Children Assistance Network',
      info7: '- International Rescue Committee',
      info8: '- LUNA and Gates Consulting Group',
      info9: '- Sacred Heart Community Service',
      info10: '- San Jose Public Library Foundation',
      info11: '- Tech Exchange',
      // info:
        // 'Coloring book forage photo booth gentrify lumbersexual. Migas chillwave poutine synth shoreditch, enamel pin thundercats fashion axe roof party polaroid chartreuse.',
    },
    {
      id: 3,
      title: 'DIF GRANTEES - Fiscal Year 2020',
      ifOpen: false,
      info1: '- ACE Charter Schools',
      info2: '- Alum Rock Union School District ',
      info3: '- Catholic Charities of Santa Clara County ',
      info3: '- City of San Jose - Parks, Recreation & Neighborhood Services',
      info4: '- CreaTV San Jose',
      info5: '- Cristo Rey San José High School',
      info6: '- First Community Housing',
      info7: '- Goodwill of Silicon Valley',
      info8: '- Indian Health Center of Santa Clara Valley',
      info9: '- International Children Assistance Network',
      info10: '- International Rescue Committee',
      info11: '- LUNA and Gates Consulting Group',
      info12: '- LitLab',
      info13: '- NPower Inc.',
      info14: '- Rocketship Public Schools',
      info15: '- Sacred Heart Community Service',
      info16: '- San Jose Public Library Foundation',
      info17: '- Step Up and Do Something! Inc.',
      info18: '- Tech Exchange',
      info19: '- Third Street Community Center',
      info20: '- Vietnamese Voluntary Foundation',
      // info:
        // 'Enamel pin fam sustainable woke whatever venmo. Authentic asymmetrical put a bird on it, lumbersexual activated charcoal kinfolk banjo cred pickled sartorial.',
    },
   
  ]
  export default questions