const PopularData = [
  {
    id: 1,
    image: "images/popular1.jpg",
    country: "Italy",
    name: "What is a wifi hotspot? What is its benefit and how to access one?",
    vid: "https://www.youtube.com/embed/g71vtOuhL1k",
  },
  {
    id: 2,
    image: "images/popular2.jpg",
    country: "Mexico",
    name: "What is a wifi hotspot? What is its benefit and how to access one?",
    vid: "https://www.youtube.com/embed/g71vtOuhL1k",
    price: "$400.00",
  },
  {
    id: 3,
    image: "images/popular3.jpg",
    country: "United States",
    name: "What is a wifi hotspot? What is its benefit and how to access one?",
    vid: "https://www.youtube.com/embed/g71vtOuhL1k",
    price: "$500.00",
  },
  {
    id: 4,
    image: "images/popular4.jpg",
    country: "Thailand",
    name: "What is a wifi hotspot? What is its benefit and how to access one?",
    vid: "https://www.youtube.com/embed/g71vtOuhL1k",
    price: "$100.00",
  },
  {
    id: 5,
    image: "images/popular5.jpg",
    country: "Vietnam",
    name: "What is a wifi hotspot? What is its benefit and how to access one?",
    vid: "https://www.youtube.com/embed/g71vtOuhL1k",
    price: "$200.00",
  },
  {
    id: 6,
    image: "images/popular2.jpg",
    country: "Mexico",
    name: "What is a wifi hotspot? What is its benefit and how to access one?",
    vid: "https://www.youtube.com/embed/g71vtOuhL1k",
    price: "$400.00",
  },
  {
    id: 7,
    image: "images/popular3.jpg",
    country: "United States",
    name: "What is a wifi hotspot? What is its benefit and how to access one?",
    vid: "https://www.youtube.com/embed/g71vtOuhL1k",
    price: "$500.00",
  },
  {
    id: 8,
    image: "images/popular4.jpg",
    country: "Thailand",
    name: "What is a wifi hotspot? What is its benefit and how to access one?",
    vid: "https://www.youtube.com/embed/g71vtOuhL1k",
    price: "$100.00",
  },
]

export default PopularData
